### 获取当前用户余额信息
GET http://127.0.0.1:9002/imooc/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiNTRiMTBjNGQtZGU3Zi00MGFiLWIyNjAtMzM3YzUxMTRiOTI2IiwiZXhwIjoxNzE3MzQ0MDAwfQ.BfoiOFHQXwJFWpS0p8V1pYeIFD79Oj9Zre7GkUv82S7v8GuYxBUdDaaLQXpPPA8DT-Oa8Kna9VA_xfOC10LrsLsJR-R6RQU3segX-MJHwgZ98rbCxzdSCHBc8-lvz-_JbVNQr71Aq5oteA5CQAVKvdAEyDmJNCw0D6itCs1H0SYOiKzM0DPNN0NBpkyYbZ1faT4Q9RNnCgzrmsK7oz-sBZapUfj4r6xfAB7hjLXv7WdSJHBGfEEU-bXx6I5b4D5AWOhWKdz91DfQD21TurjLrbMs2CqC4kUGGwuWR1nZGrJwLcIM07ZX1HIO6sUDHbzx4EQImiQismya6ORzoPObhA

### 扣减用户余额
PUT http://127.0.0.1:9002/imooc/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiNTRiMTBjNGQtZGU3Zi00MGFiLWIyNjAtMzM3YzUxMTRiOTI2IiwiZXhwIjoxNzE3MzQ0MDAwfQ.BfoiOFHQXwJFWpS0p8V1pYeIFD79Oj9Zre7GkUv82S7v8GuYxBUdDaaLQXpPPA8DT-Oa8Kna9VA_xfOC10LrsLsJR-R6RQU3segX-MJHwgZ98rbCxzdSCHBc8-lvz-_JbVNQr71Aq5oteA5CQAVKvdAEyDmJNCw0D6itCs1H0SYOiKzM0DPNN0NBpkyYbZ1faT4Q9RNnCgzrmsK7oz-sBZapUfj4r6xfAB7hjLXv7WdSJHBGfEEU-bXx6I5b4D5AWOhWKdz91DfQD21TurjLrbMs2CqC4kUGGwuWR1nZGrJwLcIM07ZX1HIO6sUDHbzx4EQImiQismya6ORzoPObhA

{
  "userId": 10,
  "balance": 2000
}
