###查询服务
GET http://localhost:9002/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEzLFwidXNlcm5hbWVcIjpcInNodW9saUBnb2QuY29tXCJ9IiwianRpIjoiNzhhODBkZjktMTBiMi00YTMzLWI5ZjQtODFjOWMyOThlNDUxIiwiZXhwIjoxNzE2OTk4NDAwfQ.njmzqRRAkFr5ox70yuNwCf3O9lnq1p-jsqwARJvtLFfToRcBQjvRiEJp0RZ0EntvrxSOJhOrkpwHX3jjSXDXN4xgyzHq7w7sFN9_sh5ova46VJ16_4B_tKz462vxbLL4GLXDD8i37ASyt83KX2VGxAQ0AvShVUBmN93Loe4_RSrA47Dngx9hj-9_G0KtmAdc20iRN-OYt1DxsP884C7V4DXaGGGbI_L0nE8RO_e8woshAaFm0SZXaP_aAL5pd7N7QOO9wBXlnqR4CfhqSXxn2hzpiWarMCK9GhNahofWU7xsSbTyjwiRxPcKMqqHrBx5NVGpoIZqPJYIw4nmoI3o6Q
token: imooc
