###查询服务
GET http://localhost:9002/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiMWI0NTllNTAtZDZhMS00ZTU4LTljODItY2M2MjNmOTgzZWZmIiwiZXhwIjoxNzE3MDg0ODAwfQ.Kii-q8jbrs0bJiDBanDPsEugtiPsYmvxJmVy84ifVI2HpEYQC8BXyjbHF_Cxxd3QAA4-Rx6MbVI5LA4pdaVIjBu3gYttgZe11UKc2UNMaqW1eBZRsjpWccaDJhtQRVzafBwFtIpBQDAUWZcJmnBnnerV3EmlbYuGOtycR13bG6ndhaGhaY_pKkSthd65adagt96warXyHtJAOIp1rouRy2aA20noHACn9LbGlRVvhWjHAAirsFO0Q9H0rf8cKSEt7Buii_KMuC_SbnsgepTSaUlkUtmp6bjxTX5uPAjgo22r7TI1eDnJwITVRKU3DB9hU5o7Ujobs21YtCBt9bJeow
token: imooc
