### 根据 TableId 查询详细商品信息
POST http://127.0.0.1:9002/imooc/ecommerce-goods-service/goods/goods-info
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiZGNkMzFkODItYzFiMi00NTg1LTk3YzgtYzZlOGE1YzNiY2JlIiwiZXhwIjoxNzE3Njg5NjAwfQ.nCGh0DK6piSYYhLqhAsh-bjbiAupf8eappecD0au6BeMTkMH7C3BqY-Dcksz38ACcThpGWT7cROYc-FmO3_oRhiPXqVnb0BjZXT8HwznAPxNlknTR2MFH6km0bZ6e7XdfTFyrIpNyHD_csvMhCum-wGzoaMjayRfuACThY1TFojl4ExleF451exVXiD1YJWCsMsrFjotOL41Ibzh4OBlMnEU9sdjSKj5W8ntiJ48opiTXOza-hz9ydsBsjEdyLITVNS_inlN9a7J4C8ktocRs6EBhk4koYGmFUI0Vk5tvR8DZ4VeJtyRBo_E2mwyN59AhFXMA4tJrDclGCN6vYiJWg

{
  "ids": [
    {
      "id": 22
    },
    {
      "id": 23
    }
  ]
}


### 根据分页查询简单商品信息
GET http://127.0.0.1:9002/imooc/ecommerce-goods-service/goods/page-simple-goods-info?page=2
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiZGNkMzFkODItYzFiMi00NTg1LTk3YzgtYzZlOGE1YzNiY2JlIiwiZXhwIjoxNzE3Njg5NjAwfQ.nCGh0DK6piSYYhLqhAsh-bjbiAupf8eappecD0au6BeMTkMH7C3BqY-Dcksz38ACcThpGWT7cROYc-FmO3_oRhiPXqVnb0BjZXT8HwznAPxNlknTR2MFH6km0bZ6e7XdfTFyrIpNyHD_csvMhCum-wGzoaMjayRfuACThY1TFojl4ExleF451exVXiD1YJWCsMsrFjotOL41Ibzh4OBlMnEU9sdjSKj5W8ntiJ48opiTXOza-hz9ydsBsjEdyLITVNS_inlN9a7J4C8ktocRs6EBhk4koYGmFUI0Vk5tvR8DZ4VeJtyRBo_E2mwyN59AhFXMA4tJrDclGCN6vYiJWg


### 根据 TableId 查询简单商品信息: 完整的 goods cache
### 第二步验证, 删掉 cache
### 第三步验证, 删除 cache 中其中一个商品
POST http://127.0.0.1:9002/imooc/ecommerce-goods-service/goods/simple-goods-info
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiZGNkMzFkODItYzFiMi00NTg1LTk3YzgtYzZlOGE1YzNiY2JlIiwiZXhwIjoxNzE3Njg5NjAwfQ.nCGh0DK6piSYYhLqhAsh-bjbiAupf8eappecD0au6BeMTkMH7C3BqY-Dcksz38ACcThpGWT7cROYc-FmO3_oRhiPXqVnb0BjZXT8HwznAPxNlknTR2MFH6km0bZ6e7XdfTFyrIpNyHD_csvMhCum-wGzoaMjayRfuACThY1TFojl4ExleF451exVXiD1YJWCsMsrFjotOL41Ibzh4OBlMnEU9sdjSKj5W8ntiJ48opiTXOza-hz9ydsBsjEdyLITVNS_inlN9a7J4C8ktocRs6EBhk4koYGmFUI0Vk5tvR8DZ4VeJtyRBo_E2mwyN59AhFXMA4tJrDclGCN6vYiJWg

{
  "ids": [
    {
      "id": 22
    },
    {
      "id": 23
    }
  ]
}


### 扣减商品库存
PUT http://127.0.0.1:9002/imooc/ecommerce-goods-service/goods/deduct-goods-inventory
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInNodW9saUBkZXYuY29tXCJ9IiwianRpIjoiZGNkMzFkODItYzFiMi00NTg1LTk3YzgtYzZlOGE1YzNiY2JlIiwiZXhwIjoxNzE3Njg5NjAwfQ.nCGh0DK6piSYYhLqhAsh-bjbiAupf8eappecD0au6BeMTkMH7C3BqY-Dcksz38ACcThpGWT7cROYc-FmO3_oRhiPXqVnb0BjZXT8HwznAPxNlknTR2MFH6km0bZ6e7XdfTFyrIpNyHD_csvMhCum-wGzoaMjayRfuACThY1TFojl4ExleF451exVXiD1YJWCsMsrFjotOL41Ibzh4OBlMnEU9sdjSKj5W8ntiJ48opiTXOza-hz9ydsBsjEdyLITVNS_inlN9a7J4C8ktocRs6EBhk4koYGmFUI0Vk5tvR8DZ4VeJtyRBo_E2mwyN59AhFXMA4tJrDclGCN6vYiJWg

[
  {
    "goodsId": 22,
    "count": 100
  },
  {
    "goodsId": 23,
    "count": 34
  }
]
